exclude: '.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.0
  hooks:
  - id: commitizen
    stages: [commit-msg]
