exclude: .git|.tox
default_stages:
- commit
fail_fast: true
repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: 3.12.0
    hooks:
    -   id: commitizen
        stages:
        - commit-msg
