site_name: Example wiki
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: 'index.md'
  - Project: 
    - 'Structure': 'Project/project.md'
    - 'Test': 'Project/testing/test.md'
    - Source:
      - 'src': 'Project/src/src.md'
      - 'components': "Project/src/components/components.md"
  - MkDocs:
    - 'Writing MkDocs': 'MkDocs/mkdocs-writing.md'
    - 'CI/CD With MkDocs': 'MkDocs/mkdocs-ci.md'
  - CI/CD:
    - 'Contiuous integration': 'CI/ci.md'
  - Git prehooks:
    - 'prehooks': 'git/prehooks.md'
  - GitHub issues and kanban board:
    - Issues: 'github/issues.md'
    - Kanban board: 'github/kanban.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  version:
    provider: mike