on:
  pull_request:
    types:
      - closed
  
  # have to get artifact or run deployment workflow again
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    timeout-minutes: 30 #job times out after 30 mins
    steps:
    - name: Deploy
      run: |
        echo The PR was merged
