---
on:
  pull_request:
    types:
      - closed
  
  # have to get artifact or run deployment workflow again
jobs: 
  if_merged:
    if: github.event.pull_request.merged == true
    name: Build and create a docker image
    runs-on: ubuntu-22.04
    timeout-minutes: 30 #job times out after 30 mins
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar

