name: vue-3-ci-cd

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'wiki/**'

permissions:
  contents: read # The workflow is read only

# Ensures that only one workflow per branch/environment will be run
concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30 #job times out after 30 mins

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Change this to the desired Node.js version

    # Cache dependencies for faster workflow
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
          path: ~/.npm # Can potentially create cache of /node_modules folder but could create conflicts
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: | 
          npm run test:unit
          npm run test:coverage 

    - name: Retrieve unit test coverage
      run: |
          COVERAGE_VAR=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          if [[ $COVERAGE_VAR -lt 120 ]]; then  # Adjust threshold as needed
            echo "::warning::Coverage below threshold (${COVERAGE_VAR}). Please improve test coverage."
          else
            echo "$COVERAGE_VAR % line coverage"
          fi

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

