name: vue-3-ci-cd

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'wiki/**'

permissions:
  contents: read # The workflow is read only

# Ensures that only one workflow per branch/environment will be run
concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30 #job times out after 30 mins

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Change this to the desired Node.js version

    # Cache dependencies for faster workflow
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
          path: ~/.npm # Can potentially create cache of /node_modules folder but could create conflicts
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: | 
          npm run test:unit
          npm run test:coverage 

    - name: Retrieve unit test coverage
      run: |
          # Replace with commands to retrieve and parse the coverage report
          coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          echo "Coverage: $coverage"     
    - name: Compare coverage with threshold and notify
      if: ${{ steps.retrieve_coverage.outputs.coverage < 80 }}  # Adjust threshold as needed
      run: |
        echo "Coverage below threshold. Please improve test coverage."
        # Add commands to notify users about the low coverage
    - name: Lint code
      run: npm run lint # Change this to your linting command

    - name: Build
      run: npm run build # Change this to your build command

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

