name: mkdocs-ci

on:
  push:
    branches:
      - main
      - documentation

permissions:
  contents: write

jobs:

  super-linter:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: github/super-linter@v5
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: \.md$
          VALIDATE_ALL_CODEBASE: False

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: 'mlc_config.json'
        folder-path: 'wiki/'


  deploy:
    needs: [super-linter, markdown-link-check] 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material pillow cairosvg

      - name: Build and Deploy MkDocs
        run: |
          cd wiki
          mkdocs build
          mkdocs gh-deploy --force
